name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2.2.1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"