name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28 #v3
      - uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1 #v2.2.1
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b #v1
      - run: ./gradlew build
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"