name: build and publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2.2.1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew x64zip arm64zip
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: |
            build/distributions/pin-github-actions-x64.zip
            build/distributions/pin-github-actions-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
